name: 'Validate Plugin Build'
description: 'Validate plugin build files and versions'

inputs:
  PLUGIN_SLUG:
    required: true
    description: 'Plugin slug name'
  PLUGIN_VERSION:
    required: true
    description: 'Plugin version to validate'

runs:
  using: 'composite'
  steps:
    - name: Validate build files
      shell: bash
      env:
        PLUGIN_SLUG: ${{ inputs.PLUGIN_SLUG }}
        PLUGIN_VERSION: ${{ inputs.PLUGIN_VERSION }}
      run: |
        echo "🔍 Validating plugin build files..."
        echo "Plugin: $PLUGIN_SLUG"
        echo "Version: $PLUGIN_VERSION"
        
        # Use existing validation script
        bash "${GITHUB_WORKSPACE}/.github/scripts/validate-build-files.sh"
        
        echo "✅ Plugin build validation completed successfully"
