name: 'Prepare Plugin Environment'
description: 'Extract plugin version and slug from package.json'

outputs:
  PACKAGE_VERSION:
    description: 'Plugin version from package.json'
    value: ${{ steps.extract-info.outputs.PACKAGE_VERSION }}
  PLUGIN_SLUG:
    description: 'Plugin slug from package.json'
    value: ${{ steps.extract-info.outputs.PLUGIN_SLUG }}

runs:
  using: 'composite'
  steps:
    - name: Extract plugin information
      id: extract-info
      shell: bash
      run: |
        echo "📦 Extracting plugin information from package.json..."
        
        # Validate package.json exists
        if [ ! -f "package.json" ]; then
          echo "❌ Error: package.json not found"
          exit 1
        fi
        
        # Extract version and slug
        PACKAGE_VERSION=$(cat package.json | jq -r '.version')
        PLUGIN_SLUG=$(cat package.json | jq -r '.name')
        
        # Validate extracted values
        if [ "$PACKAGE_VERSION" = "null" ] || [ -z "$PACKAGE_VERSION" ]; then
          echo "❌ Error: Could not extract version from package.json"
          exit 1
        fi
        
        if [ "$PLUGIN_SLUG" = "null" ] || [ -z "$PLUGIN_SLUG" ]; then
          echo "❌ Error: Could not extract name from package.json"
          exit 1
        fi
        
        # Output values
        echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV
        echo "PLUGIN_SLUG=$PLUGIN_SLUG" >> $GITHUB_ENV
        echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_OUTPUT
        echo "PLUGIN_SLUG=$PLUGIN_SLUG" >> $GITHUB_OUTPUT
        
        echo "✅ Plugin information extracted successfully:"
        echo "   - Plugin: $PLUGIN_SLUG"
        echo "   - Version: $PACKAGE_VERSION"
