name: One-Click Release (Enhanced Deploy)

on:
  workflow_dispatch:

jobs:
  build:
    if: ( github.actor == 'TzviRabinovitch' || github.actor == 'hein-obox' || github.actor == 'KingYes' || github.actor == 'bainternet'  || github.actor == 'arielk' || github.actor == 'nuritsha' || github.actor == 'nicoladj77' ) && startsWith( github.repository, 'elementor/' )
    uses: ./.github/workflows/build.yml
    secrets: inherit

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Prepare Plugin Environment
        id: plugin-env
        uses: ./.github/actions/prepare-plugin-env
        
      - name: Build Plugin
        id: build-plugin
        uses: ./.github/actions/build-plugin
        with:
          PLUGIN_SLUG: ${{ steps.plugin-env.outputs.PLUGIN_SLUG }}
          
      - name: Install SVN Tools
        uses: ./.github/actions/install-svn
        
      - name: Validate Plugin Build
        uses: ./.github/actions/validate-plugin-build
        with:
          PLUGIN_SLUG: ${{ steps.plugin-env.outputs.PLUGIN_SLUG }}
          PLUGIN_VERSION: ${{ steps.plugin-env.outputs.PACKAGE_VERSION }}
          
      - name: Deploy to WordPress.org
        uses: ./.github/actions/deploy-to-wordpress-org
        with:
          PLUGIN_SLUG: ${{ steps.plugin-env.outputs.PLUGIN_SLUG }}
          PLUGIN_VERSION: ${{ steps.plugin-env.outputs.PACKAGE_VERSION }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
